name: "ocr_app"
platform: "ensemble"
max_batch_size: 0

input [
    {
        name: "image_b64"
        data_type: TYPE_STRING
        dims: [ 1 ]
    },
    {
        name: "params"
        data_type: TYPE_STRING
        dims: [ 1 ]
        optional: true
    }
]

output [
    {
        name: "ocr_results",
        data_type: TYPE_STRING,
        dims: [ 1 ]
    }
]


ensemble_scheduling {
  step [
    {
      model_name: "image_decode"
      model_version: -1
      input_map {
        key: "image_b64"
        value: "image_b64"
      }
      output_map {
        key: "image"
        value: "image"
      }
    },
    {
      model_name: "ocr_mrcnn_algo"
      model_version: -1
      input_map {
        key: "image"
        value: "image"
      }
      input_map {
        key: "params"
        value: "params"
      }
      output_map {
        key: "boxes"
        value: "boxes"
      }
      output_map {
        key: "box_scores"
        value: "box_scores"
      }
    },
    {
      model_name: "ocr_app_intermediate"
      model_version: -1
      input_map {
        key: "image"
        value: "image"
      }
      input_map {
        key: "boxes"
        value: "boxes"
      }
      input_map {
        key: "params"
        value: "params"
      }
      output_map {
        key: "crop_images"
        value: "crop_images"
      }
      output_map {
        key: "crop_images_shape"
        value: "crop_images_shape"
      }
      output_map {
        key: "groups"
        value: "groups"
      }
    },
    {
      model_name: "ocr_transformer_algo"
      model_version: -1
      input_map {
        key: "image"
        value: "crop_images"
      }
      input_map {
        key: "image_shape"
        value: "crop_images_shape"
      }
      input_map {
        key: "params"
        value: "params"
      }
      output_map {
        key: "while/Exit_1"
        value: "reg_texts"
      }
    },
    {
      model_name: "ocr_app_post"
      model_version: -1
      input_map {
        key: "image"
        value: "image"
      }
      input_map {
        key: "boxes"
        value: "boxes"
      }
      input_map {
        key: "box_scores"
        value: "box_scores"
      }
      input_map {
        key: "reg_texts"
        value: "reg_texts"
      }
      input_map {
        key: "groups"
        value: "groups"
      }
      input_map {
        key: "params"
        value: "params"
      }
      output_map {
        key: "ocr_results"
        value: "ocr_results"
      }
    }
  ]
}

