name: "ocr_mrcnn_trt_graph"
backend: "tensorrt"
max_batch_size: 0

input [
    {
        name: "image"
        data_type: TYPE_FP32
        dims: [ 1, 1600, 1600, 3 ]
    }
]

output [
    {
        name: "output_detections",
        data_type: TYPE_FP32,
        dims: [ 300, 8 ]
    },
    {
        name: "output_masks",
        data_type: TYPE_FP32,
        dims: [ 300, 1, 28, 28 ]
    }
]

version_policy: { all { }}

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]