basic_config {
  gpu_config {
    parameters {
      key: "devices"
      value: "0"
    }
  }
}

model {
  name: "ocr_format_elem"
  type: "dataelem.graph.ocr_format_elem"
  path: "ocr_format"
  instance_group { count: 1, kind: KIND_CPU }
}

model {
  name: "general_text_det_mrcnn_v2.0"
  type: "dataelem.alg.MaskRCNN"
  parameters {
    key: "dep_model_name"
    value: "general_text_det_mrcnn_v2.0_graph"
  }
  instance_group { count: 3, kind: KIND_CPU }
  dep {
    name: "general_text_det_mrcnn_v2.0_graph"
    type: "dataelem.graph.MaskRCNNV5GraphTf"
    instance_group { kind: KIND_GPU }
  }
}

model {
  name: "transformer-blank-v0.2-faster"
  type: "dataelem.alg.TransformerV1"
  parameters {
    key: "dep_model_name"
    value: "transformer-blank-v0.2_trt transformer_blank_v0.2_post"
  }
  parameters { key: "downsample_rate", value: "8" }
  parameters { key: "use_trt", value: "1" }
  instance_group { count: 3, kind: KIND_CPU }
  dep {
    name: "transformer-blank-v0.2_trt"
    type: "dataelem.graph.TransformerGraphTrt"
    instance_group { kind: KIND_GPU }
  }
  dep {
    name: "transformer_blank_v0.2_post"
    type: "dataelem.graph.TransformerPostGraph"
    instance_group { kind: KIND_GPU }
  }
}

model {
  name: "transformer-hand-v1.16-faster"
  type: "dataelem.alg.TransformerV1"
  parameters {
    key: "dep_model_name"
    value: "transformer-hand-v1.16_trt transformer_hand_post_graph"
  }
  parameters { key: "use_trt", value: "1" }
  instance_group { count: 3, kind: KIND_CPU }
  dep {
    name: "transformer-hand-v1.16_trt"
    type: "dataelem.graph.TransformerGraphTrt"
    instance_group { kind: KIND_GPU }
  }
  dep {
    name: "transformer_hand_post_graph"
    type: "dataelem.graph.TransformerPostGraph"
    instance_group { kind: KIND_GPU }
  }
}

model {
  name: "std_checkbox"
  type: "dataelem.alg.MaskRCNN"
  parameters { key: "dep_model_name", value: "det_std_checkbox" }
  instance_group { count: 3, kind: KIND_CPU }
  dep {
    name: "det_std_checkbox"
    type: "dataelem.graph.MaskRCNNV5GraphTf"
    instance_group { kind: KIND_GPU }
  }
}

model {
  name: "checkbox_post"
  type: "dataelem.graph.checkbox_post"
  instance_group { count: 1, kind: KIND_CPU }
}

model {
  name: "general_prep"
  type: "dataelem.graph.general_prep"
  parameters { key: "dep_model_name", value: "erase_net erase_net_wm" }
  path: "general_prep"
  instance_group { count: 1, kind: KIND_CPU }
  dep {
    name: "erase_net"
    type: "dataelem.graph.erase_net"
    instance_group { kind: KIND_GPU }
  }
  dep {
    name: "erase_net_wm"
    type: "dataelem.graph.erase_net_wm"
    instance_group { kind: KIND_GPU }
  }
}
