name: "seal_text_reg_algo"
backend: "dataelem_python"
max_batch_size: 0

parameters { key: "algorithm_type" value: { string_value: "OcrTransformer" } }
parameters { key: "dep_model_name" value: { string_value: "seal_text_reg_graph" } }
parameters { key: "fixed_height" value: { string_value: "32" } }
parameters { key: "W_min" value: { string_value: "40" } }
parameters { key: "W_max" value: { string_value: "800" } }
parameters { key: "downsample_rate" value: { string_value: "4" } }
parameters { key: "input_channels" value: { string_value: "3" } }
parameters { key: "batch_size" value: { string_value: "64" } }

input [
    {
        name: "image"
        data_type: TYPE_FP32
        dims: [ -1, -1, -1, -1 ]
    },
    {
        name: "image_shape"
        data_type: TYPE_INT32
        dims: [ -1, 2 ]
    },
    {
        name: "params"
        data_type: TYPE_STRING
        dims: [ 1 ]
        optional: true
    }
]

output [
    {
        name: "while/Exit_1",
        data_type: TYPE_STRING,
        dims: [ -1 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]