name: "ocr_app"
backend: "dataelem_python"
max_batch_size: 0

parameters { key: "app_type" value: { string_value: "OcrApp" } }
parameters { key: "det_model_name" value: { string_value: "ocr_mrcnn_trt_algo" } }
parameters { key: "det_model_version" value: { string_value: "-1" } }
parameters { key: "reg_model_name" value: { string_value: "ocr_transformer_trt_algo" } }
parameters { key: "reg_model_version" value: { string_value: "-1" } }

input [
    {
        name: "image_b64"
        data_type: TYPE_STRING
        dims: [ 1 ]
    },
    {
        name: "params"
        data_type: TYPE_STRING
        dims: [ 1 ]
        optional: true
    }
]

output [
    {
        name: "ocr_results",
        data_type: TYPE_STRING,
        dims: [ 1 ]
    }
]

version_policy: { all { }}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]