name: "seal_app"
backend: "dataelem_python"
max_batch_size: 0

parameters { key: "app_type" value: { string_value: "SealApp" } }

parameters { key: "seal_det_model_name" value: { string_value: "seal_detect_algo" } }
parameters { key: "seal_det_model_version" value: { string_value: "-1" } }

parameters { key: "seal_curve_text_det_model_name" value: { string_value: "seal_curve_text_det_algo" } }
parameters { key: "seal_curve_text_det_model_version" value: { string_value: "-1" } }

parameters { key: "seal_quad_text_det_model_name" value: { string_value: "seal_quad_text_det_algo" } }
parameters { key: "seal_quad_text_det_model_version" value: { string_value: "-1" } }

parameters { key: "seal_text_reg_model_name" value: { string_value: "seal_text_reg_algo" } }
parameters { key: "seal_text_reg_model_version" value: { string_value: "-1" } }

input [
    {
        name: "image_b64"
        data_type: TYPE_STRING
        dims: [ 1 ]
    },
    {
        name: "params"
        data_type: TYPE_STRING
        dims: [ 1 ]
        optional: true
    }
]

output [
    {
        name: "seal_results",
        data_type: TYPE_STRING,
        dims: [ 1 ]
    }
]

version_policy: { all { }}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]