name: "ocr_mrcnn_postprocess"
backend: "dataelem_python"
max_batch_size: 0

parameters { key: "algorithm_type" value: { string_value: "OcrMrcnnPostProcess" } }

input [
    {
        name: "output/scores",
        data_type: TYPE_FP32,
        dims: [ -1 ]
    },
    {
        name: "output/masks",
        data_type: TYPE_FP32,
        dims: [ -1, 28, 28 ]
    },
    {
        name: "output/boxes",
        data_type: TYPE_FP32,
        dims: [ -1, 4 ]
    },
    {
        name: "output/boxes_cos",
        data_type: TYPE_FP32,
        dims: [ -1 ]
    },
    {
        name: "output/boxes_sin",
        data_type: TYPE_FP32,
        dims: [ -1 ]
    },
    {
        name: "params"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

output [
    {
        name: "boxes",
        data_type: TYPE_FP32,
        dims: [ -1, 4, 2 ]
    },
    {
        name: "box_scores",
        data_type: TYPE_FP32,
        dims: [ -1 ]
    }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]